"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

import { createTrainingRun } from "@/features/labs/gradient-descent/api";
import { LossChart } from "@/features/labs/gradient-descent/loss-chart";
import { TimelineControls } from "@/features/labs/gradient-descent/timeline-controls";
import { ClassificationPlot } from "@/features/labs/logistic-regression/classification-plot";
import { useTrainingTimeline } from "@/features/timeline/use-training-timeline";
import type { TrainingRun, TrainingRunRequest } from "@/types/training-run";

const baseRequest: TrainingRunRequest = { algorithm: "logistic_regression", dataset: { samples: 64, noise: 0.1, seed: 0 }, training: { learning_rate: 0.1, epochs: 50, initial_weight: 0, initial_bias: 0 } };

export function LogisticComparison() {
      const [runA, setRunA] = useState<TrainingRun | null>(null); const [runB, setRunB] = useState<TrainingRun | null>(null); const [learningRateA, setLearningRateA] = useState(0.1); const [learningRateB, setLearningRateB] = useState(0.5); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
      const timeline = useTrainingTimeline(runA, runA && runB ? Math.min(runA.history.length, runB.history.length) : undefined);
      const stateA = timeline.selectedTrainingState; const stateB = runB?.history[timeline.currentStep] ?? null;
      const trainComparison = useCallback(async (rateA: number, rateB: number) => { setLoading(true); setError(null); try { const [nextA, nextB] = await Promise.all([createTrainingRun(makeRequest(rateA)), createTrainingRun(makeRequest(rateB))]); setRunA(nextA); setRunB(nextB); } catch (caught) { setError(caught instanceof Error ? caught.message : "The comparison could not be trained."); } finally { setLoading(false); } }, []);
      useEffect(() => { const timer = window.setTimeout(() => void trainComparison(0.1, 0.5), 0); return () => window.clearTimeout(timer); }, [trainComparison]);
      const run = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void trainComparison(learningRateA, learningRateB); };
      return <div className="lab-layout"><section className="lab-intro"><div className="lab-intro-copy"><p className="eyebrow">Lab 04 / shared classification review</p><h1>Two classifiers. One clock.</h1><p>Compare how different learning rates move the same logistic decision boundary.</p></div><form className="training-form" onSubmit={run}><div className="form-heading"><div><p className="eyebrow">Comparison setup</p><h2>Learning rates</h2></div><span className="run-status">{loading ? "Recording" : runA && runB ? "Ready" : "Waiting"}</span></div><NumberControl label="Run A learning rate" value={learningRateA} onChange={setLearningRateA} /><NumberControl label="Run B learning rate" value={learningRateB} onChange={setLearningRateB} /><button className="primary-button run-button" disabled={loading} type="submit">{loading ? "Training comparison..." : "Train comparison"}</button></form></section>{error && <section className="lab-alert" role="alert">{error}</section>}{!loading && runA && runB && <><div className="comparison-context"><strong>Shared step: {timeline.currentStep}</strong><span>Shared range: 0-{Math.max(Math.min(runA.history.length, runB.history.length) - 1, 0)}</span></div><section className="comparison-grid"><ComparisonPanel label="Run A" run={runA} state={stateA} currentStep={timeline.currentStep} /><ComparisonPanel label="Run B" run={runB} state={stateB} currentStep={timeline.currentStep} /></section><TimelineControls currentStep={timeline.currentStep} isPlaying={timeline.isPlaying} markers={[]} onAddMarker={() => undefined} onBackward={timeline.stepBackward} onForward={timeline.stepForward} onJump={timeline.jumpToStep} onPlayToggle={timeline.togglePlay} onRemoveMarker={() => undefined} onReset={timeline.reset} onSpeed={timeline.setPlaybackSpeed} playbackSpeed={timeline.playbackSpeed} reducedMotion={timeline.reducedMotion} totalSteps={timeline.totalSteps} /></>}</div>;
}

function makeRequest(learningRate: number): TrainingRunRequest { return { ...baseRequest, training: { ...baseRequest.training, learning_rate: learningRate } }; }
function NumberControl({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="number-control"><span>{label}</span><input max="2" min="0.001" onChange={(event) => onChange(Number(event.target.value))} required step="0.001" type="number" value={value} /></label>; }
function ComparisonPanel({ label, run, state, currentStep }: { label: string; run: TrainingRun; state: TrainingRun["history"][number] | null; currentStep: number }) { return <section className="comparison-run-panel"><div className="comparison-run-heading"><div><p className="eyebrow">{label}</p><h2>Logistic regression</h2></div><span>{run.history.length} frames</span></div><div className="comparison-charts"><ClassificationPlot points={run.dataset_points} state={state} /><LossChart currentStep={currentStep} history={run.history} label="Binary Cross-Entropy" /></div><div className="comparison-state"><h3>{state ? `Step ${state.step}` : "No state available"}</h3>{state && <dl className="comparison-metrics"><div><dt>Accuracy</dt><dd>{state.metrics.accuracy?.toLocaleString(undefined, { maximumFractionDigits: 5 }) ?? "N/A"}</dd></div><div><dt>BCE</dt><dd>{state.loss.toLocaleString(undefined, { maximumFractionDigits: 5 })}</dd></div></dl>}</div></section>; }