import { SectionPage } from "@/components/layout/section-page";
import Link from "next/link";

const lessons = [
  { href: "/labs/gradient-descent", tag: "Foundations / 01", title: "What is machine learning?", summary: "Models learn patterns from data rather than memorizing one fixed answer.", idea: "Use data to find structure and make predictions.", concepts: ["features", "targets", "predictions"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 02", title: "Features, targets, and predictions", summary: "A feature is the input signal; a target is the value we want to predict.", idea: "The model turns inputs into predictions and reduces the gap to the target.", concepts: ["features", "targets", "loss"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 03", title: "Training vs inference", summary: "Training fits parameters. Inference uses those parameters on new examples.", idea: "One stage learns, the other stage predicts.", concepts: ["training", "inference"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 04", title: "Loss functions", summary: "Loss measures how far predictions are from the target values.", idea: "A lower loss means the model has aligned better with the data.", concepts: ["loss", "MSE"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 05", title: "Gradient descent", summary: "The model updates by moving in the direction that most reduces the loss.", idea: "Small repeated updates can reach a good minimum.", concepts: ["gradient descent", "learning rate"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/logistic-regression", tag: "Supervised / 06", title: "Logistic regression", summary: "This model produces probabilities for binary outcomes instead of raw real-valued predictions.", idea: "Classification learns a separating boundary between two classes.", concepts: ["probability", "classification", "decision boundary"], tryIt: "Open the Logistic Regression lab" },
  { href: "/labs/k-means", tag: "Unsupervised / 07", title: "K-Means clustering", summary: "K-Means groups nearby points by distance to shared centroids.", idea: "The algorithm repeatedly assigns points to clusters and moves centroids toward their mean locations.", concepts: ["clustering", "centroids", "inertia"], tryIt: "Open the K-Means lab" },
];

export default function LearnPage() {
  return <SectionPage title="Learn machine learning" description="Move from foundations to supervised and unsupervised learning. Each lesson points to a real lab where you can test the idea."><div className="space-y-6"><div className="challenge-list">{lessons.map((lesson, index) => <Link className="challenge-card" href={lesson.href} key={lesson.title}><p className="eyebrow">{lesson.tag}</p><h2>{lesson.title}</h2><p>{lesson.summary}</p><div className="mt-3 flex flex-wrap gap-2 text-xs uppercase tracking-wide text-slate-500"><span>Key idea:</span><span>{lesson.idea}</span></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><span>Concepts:</span>{lesson.concepts.map((concept) => <span key={concept}>{concept}</span>)}</div><div className="mt-4 text-sm font-medium text-teal-700">{index === 0 ? "Start this lesson" : lesson.tryIt}</div></Link>)}</div></div></SectionPage>;
}
