import { SectionPage } from "@/components/layout/section-page";
import Link from "next/link";

const lessons = [
  { href: "/labs/gradient-descent", tag: "Foundations / 01", title: "What is machine learning?", summary: "Models learn patterns from data rather than memorizing one fixed answer.", idea: "Use data to find structure and make predictions.", concepts: ["features", "targets", "predictions"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 02", title: "Features, targets, and predictions", summary: "A feature is the input signal; a target is the value we want to predict.", idea: "The model turns inputs into predictions and reduces the gap to the target.", concepts: ["features", "targets", "loss"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 03", title: "Training vs inference", summary: "Training fits parameters. Inference uses those parameters on new examples.", idea: "One stage learns, the other stage predicts.", concepts: ["training", "inference"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 04", title: "Loss functions", summary: "Loss measures how far predictions are from the target values.", idea: "A lower loss means the model has aligned better with the data.", concepts: ["loss", "MSE"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/gradient-descent", tag: "Foundations / 05", title: "Gradient descent", summary: "The model updates by moving in the direction that most reduces the loss.", idea: "Small repeated updates can reach a good minimum.", concepts: ["gradient descent", "learning rate"], tryIt: "Open the Linear Regression lab" },
  { href: "/labs/logistic-regression", tag: "Supervised / 06", title: "Logistic regression", summary: "This model produces probabilities for binary outcomes instead of raw real-valued predictions.", idea: "Classification learns a separating boundary between two classes.", concepts: ["probability", "classification", "decision boundary"], tryIt: "Open the Logistic Regression lab" },
  { href: "/labs/k-means", tag: "Unsupervised / 07", title: "K-Means clustering", summary: "K-Means groups nearby points by distance to shared centroids.", idea: "The algorithm repeatedly assigns points to clusters and moves centroids toward their mean locations.", concepts: ["clustering", "centroids", "inertia"], tryIt: "Open the K-Means lab" },
  { href: "/labs/neural-network", tag: "Deep Learning / 08", title: "Neural networks & backpropagation", summary: "Hidden layers and nonlinear activations allow networks to learn complex decision surfaces that linear models cannot separate.", idea: "The chain rule sends error signals backwards through the network to update all weights layer by layer.", concepts: ["hidden layers", "backpropagation", "chain rule", "sigmoid activation"], tryIt: "Open the Neural Network lab" },
  { href: "/labs/gradient-descent", tag: "Analysis / 09", title: "How to read a training run", summary: "Connect loss curves, gradient norms, and parameter steps to diagnose convergence, plateaus, and instability from telemetry.", idea: "Evidence from telemetry explains why parameters move and how to adjust hyperparameters.", concepts: ["loss", "gradients", "parameter updates", "convergence", "instability", "experiment comparison"], tryIt: "Explore in the Linear Regression lab" },
  { href: "/workbench", tag: "Workflow / 10", title: "Understanding datasets", summary: "Before fitting a model, inspect row counts, feature types, unique values, and missingness to understand your data surface.", idea: "Data shape, types, and quality dictate which models can learn effectively.", concepts: ["features", "datatypes", "metadata", "sample size"], tryIt: "Open the Data Workbench" },
  { href: "/workbench", tag: "Workflow / 11", title: "Missing values & imputation", summary: "Missing values disrupt linear algebra. Imputing with mean or mode allows models to process incomplete records.", idea: "Impute missing observations without inventing false correlations.", concepts: ["missing values", "mean imputation", "mode imputation"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 12", title: "Feature scaling", summary: "When features have vastly different ranges, gradients oscillate wildly. Scaling balances step sizes across dimensions.", idea: "Standardization (Z-Score) or Min-Max scaling equalizes feature magnitudes.", concepts: ["standardization", "min-max scaling", "normalization"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 13", title: "Categorical encoding", summary: "Machine learning models compute numeric dot products. One-hot encoding translates qualitative categories into binary basis indicators.", idea: "Encode categories without imposing artificial numerical ordering.", concepts: ["categorical features", "one-hot encoding", "indicator variables"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 14", title: "Train / test split", summary: "Evaluating a model on the data used to train it gives a falsely confident score. Partitioning measures generalization to new data.", idea: "Reserve a hold-out test set to evaluate real generalization.", concepts: ["training set", "test set", "reproducibility", "random seed"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 15", title: "Data leakage", summary: "If test data influences preprocessing (such as scaling or imputation means), evaluation metrics become falsely optimistic.", idea: "Fit transformers on the training partition only, then apply to test data.", concepts: ["data leakage", "pipeline isolation", "generalization integrity"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 16", title: "Evaluation metrics", summary: "Training loss is an optimization guide; evaluation metrics like MSE, MAE, R², and accuracy evaluate operational utility.", idea: "Choose metrics aligned with task objectives rather than raw loss alone.", concepts: ["MSE", "MAE", "R-squared", "evaluation metrics"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 17", title: "The confusion matrix", summary: "A 2x2 contingency table separating true positives, false positives, true negatives, and false negatives in binary classification.", idea: "Inspect exact counts of errors rather than just a single summary score.", concepts: ["confusion matrix", "true positive", "false positive", "false negative"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 18", title: "Precision vs recall", summary: "Precision asks: when the model predicts positive, how often is it right? Recall asks: what fraction of actual positives were caught?", idea: "Tuning the decision threshold adjusts the trade-off between precision and recall.", concepts: ["precision", "recall", "F1 score", "decision threshold"], tryIt: "Practice in Data Workbench" },
  { href: "/workbench", tag: "Workflow / 19", title: "Overfitting vs underfitting", summary: "Compare training and test performance to spot when a model memorizes training noise instead of general patterns.", idea: "A growing gap between train and test metrics indicates a generalization gap.", concepts: ["overfitting", "underfitting", "generalization gap"], tryIt: "Practice in Data Workbench" },
  { href: "/projects/salary-prediction", tag: "Project / 20", title: "Project: Salary Prediction", summary: "Synthesize data cleaning, train/test split, and linear regression to predict engineering compensation without data leakage.", idea: "Connect data preprocessing, training runs, and evaluation metrics into one complete ML lifecycle.", concepts: ["regression", "imputation", "one-hot encoding", "MSE", "R²", "generalization"], tryIt: "Start Project in Project Studio" },
  { href: "/projects/student-outcome", tag: "Project / 21", title: "Project: Student Exam Outcome", summary: "Build a logistic regression early-warning model to predict student admission and balance Precision vs Recall with threshold tuning.", idea: "Calibrate decision boundaries and evaluate classification ranking with confusion matrices and ROC curves.", concepts: ["classification", "decision threshold", "precision", "recall", "ROC", "AUC"], tryIt: "Start Project in Project Studio" },
  { href: "/projects/customer-segmentation", tag: "Project / 22", title: "Project: Customer Segmentation", summary: "Segment retail shoppers with unsupervised K-Means, standardizing features to discover cohesive behavioral cohorts.", idea: "Standardize multi-scale features and evaluate clustering cohesion using inertia and centroid analysis.", concepts: ["unsupervised learning", "clustering", "feature scaling", "inertia", "centroids"], tryIt: "Start Project in Project Studio" },
];

export default function LearnPage() {
  return <SectionPage title="Learn machine learning" description="Move from foundations to supervised and unsupervised learning. Each lesson points to a real lab where you can test the idea."><div className="space-y-6"><div className="challenge-list">{lessons.map((lesson, index) => <Link className="challenge-card" href={lesson.href} key={lesson.title}><p className="eyebrow">{lesson.tag}</p><h2>{lesson.title}</h2><p>{lesson.summary}</p><div className="mt-3 flex flex-wrap gap-2 text-xs uppercase tracking-wide text-slate-500"><span>Key idea:</span><span>{lesson.idea}</span></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><span>Concepts:</span>{lesson.concepts.map((concept) => <span key={concept}>{concept}</span>)}</div><div className="mt-4 text-sm font-medium text-teal-700">{index === 0 ? "Start this lesson" : lesson.tryIt}</div></Link>)}</div></div></SectionPage>;
}
